# 05 03 25 compiles yet to test 
# Working with Modulation
#working with moddevworking
#working crc

# CC1101    WIRE        ESP Lolin32       ESP32-30PIN
#   VCC     RED         3V3               3V3
#   GND     BLACK       GND               GND
#   MOSI    BLUE        GPIO23            GPIO23
#   SCLK    GREEN       GPIO18            GPIO18
#   MISO    YELLOW      GPIO19            GPIO19
#   GDO02   WHITE       GPIO4             GPIO4
#   GDO0    PURPLE      GPIO16            GPIO2
#   CSN     ORANGE      GPIO5             GPIO5

substitutions:
  device_name: cc1101

external_components:
  - source: github://gregb79/esphome-cc1101@passinfoworking
#external_components:
#  - source: github://gregb79/components-esphome@modulation
#    components: [ cc1101 ]


esphome:
  name: ${device_name}

esp32:
  board: nodemcu-32s
  variant: esp32
  framework:
    type: arduino

wifi:
  ssid: "Project"
  password: "project1"

 # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "OffAirIris"
    password: "12345678"

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: "4ccbb1e816a3f995343d9e144adb88f2"

web_server:
  port: 80
  version: 3

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

sensor:
  - platform: cc1101
    id: transceiver
    cs_pin: GPIO5
    gdo0: GPIO32
    gdo2: GPIO33
    bandwidth: 200
    frequency: 915985
    modulation: 0
    deviation: 160
    #rssi:
    #  name: "${device_name} rssi"
    #lqi:
    #  name: "${device_name} lqi"
  
remote_transmitter:
  - pin: GPIO16 # GDO0
    carrier_duty_percent: 100%

#remote_receiver:
#  pin: GPIO4 # GDO2
#  dump:
#    # - raw

select:
  - platform: template
    name: "SPA ELECTRIC MODE SELECT"
    id: SPA_ELECTRIC_MODE_Select
    optimistic: true
    restore_value: true
    options:
      - "Pool and Spa"
      - "Pool Only"
      - "Spa Only"
    initial_option: "Pool Only"
    set_action:
      - logger.log:
          format: "Chosen option: %s "
          args: ["x.c_str()"]

number:
  - platform: template
    name: "SPA ELECTRIC ID0 Input (249-0xF9)(J246-0xF6)"
    optimistic: true
    min_value: 0
    max_value: 255
    initial_value: 249
    step: 1
    mode: box
    id: SPA_ELECTRIC_ID0_Input

  - platform: template
    name: "SPA ELECTRIC ID1 Input (203-0xCB)(J166-0xA6)"
    optimistic: true
    min_value: 0
    max_value: 255
    initial_value: 203
    step: 1
    mode: box
    id: SPA_ELECTRIC_ID1_Input

  - platform: template
    name: "SPA ELECTRIC INSTRUCTION Input (Power 17 = 0x11)"
    optimistic: true
    min_value: 1
    max_value: 255
    initial_value: 17
    step: 1
    mode: box
    id: SPA_ELECTRIC_INSTRUCTION_Input

button:
  - platform: template
    name: "${device_name} getcode"
    on_press:
      - logger.log: "The Raw Button Was Pressed"
      - cc1101.begin_tx: transceiver
      - remote_transmitter.transmit_raw:
          code: !lambda |-
            int mode;
            if (id(SPA_ELECTRIC_MODE_Select).state == "Pool Only") {
              mode = 1;
            } else if (id(SPA_ELECTRIC_MODE_Select).state == "Spa Only") {
              mode = 2;
            } else if (id(SPA_ELECTRIC_MODE_Select).state == "Pool and Spa") {
              mode = 3;
            }
            return id(transceiver).get_data(
              (int)id(SPA_ELECTRIC_ID0_Input).state,
              (int)id(SPA_ELECTRIC_ID1_Input).state,
              (int)id(SPA_ELECTRIC_INSTRUCTION_Input).state,
              mode
            );
          repeat:
            times: 5
      - cc1101.end_tx: transceiver
      - logger.log: "The Raw Tx has happened"
